""" print("hello world!")
print(123)
print([1])
print("哈哈"+"嘻嘻")
print("哈哈"*50)

a = input("请输入:")
b = input("请输入:")
print("input输入: ",a+b)
"""
# a = input("请输入:")
# b = input("请输入:")
# print("运算的结果是:",len(a)+len(b))
# print(a)

a = (1,2,3,"哈哈")
# b = (a,"嘻嘻")
# print(b[1])
# print(a.index("哈哈"))
print(a[:4])